### ISSUE TITLE
请问下tunasync使用docker时候在workers文件传入参数有哪些

### ISSUE THREAD

**Issue by xx-zhang** [tuna/tunasync-scripts#108]
由于不知道传入参数，我当前使用宿主机调用command，接着在shell里面调用了 docker； 还在抓，但是我不清楚会不会丢失了 `size-sum` 不了解这个传入机制

## /home/scripts/cs2c.sh 
```bash
#!/bin/bash
# requires: docker 

set -e
set -o pipefail
_here=`dirname $(realpath $0)`

BASE_PATH="${TUNASYNC_WORKING_DIR}"
BASE_URL=${TUNASYNC_UPSTREAM_URL:-"http://update.cs2c.com.cn:8080"}


export REPO_SIZE_FILE=/tmp/reposize.$RANDOM

docker run --rm \
    -v $BASE_PATH:/mirrors/cs2c \
    -v /home/scripts/:/home/scripts/ \
    tunathu/tunasync-scripts \
    /bin/bash /home/scrips/cs2c_ns.sh  $BASE_URL

echo "YUM finished"
"${_here}/helpers/size-sum.sh" $REPO_SIZE_FILE --rm

```

**Comment by shankerwangmiao** [comment]
要想配合 Docker 使用 tunasync，请在配置文件中添加 `[docker]` 小节：

``` toml
[docker]
enable = true
volumes = [
  "/path/to/foo:/path/to/bar:opt"
]
```

其中 `volumes` 数组中的各个元素表示公共的需要挂载的 docker volume，内容与 `docker run` 的 `--volume` 选项一致。

然后在需要启用 Docker 的镜像配置中增加下列配置项：

``` toml
[[ mirrors ]]
# Other configurations
docker_image = "some/image:tag"
docker_options = [ "--some-opt", "opt_opt" ]
docker_volumes = [ "/path/to/other_foo:/path/to/other_bar:opt" ]
```

其中，`docker_image` 是必选配置，表示同步该镜像需要的 Docker Image 的名字，如不指定，该镜像同步时不使用 Docker；`docker_options` 数组是可选的，指定了同步该镜像启动 Docker 的时候需要的额外选项；`docker_volumes` 数组是可选的，指定了同步该镜像启动 Docker 的时候需要挂载的额外 Volume。

在同步这样的镜像的时候，tunasync 会通过 Docker 在指定的 Images 环境下执行同步指令（`command` 选项），除了配置中指定的 Volume 之外，tunasync 还会自动将目标目录挂载进 Container 中，并将环境变量 `TUNASYNC_WORKING_DIR` 指向目标目录在 Container 内部挂载的路径。
