### ISSUE TITLE
git-recursive脚本同步git仓库时，工作不正常

### ISSUE THREAD

**Issue by Fearyncess** [tuna/tunasync-scripts#161]
配置：
```toml
#/etc/tunasync/mirrors.conf.d/boost.conf 
[[mirrors]]
name = "boost.git"
provider = "command"
command = "/home/tunasync-scripts/git-recursive.sh"
upstream = "https://github.com/boostorg/boost.git"
docker_image = "tunathu/tunasync-scripts:latest"
size_pattern = "size-pack: ([0-9\\.]+[KMGTP])"
    [mirrors.env]
    MIRROR_BASE_URL="http://gm.wok.cipunited.com/"
    WORKING_DIR_BASE="/srv/git-mirror/"
    GENERATED_SCRIPT="/srv/git-mirror/boost-git.sh"
    RECURSIVE="1"
```

日志：http://fars.ee/pGah
